# Estudo do tempo

In [1]:
import pandas as pd
tempo_dia = pd.read_csv('../data/times/times_1_day.csv')
tempo_hora = pd.read_csv('../data/times/times_1_hour.csv')
tempo_minuto = pd.read_csv('../data/times/times_10_minutes.csv')

tempo_minuto['time'] = pd.to_datetime(tempo_minuto['time'], utc = True)
tempo_hora['time'] = pd.to_datetime(tempo_hora['time'], utc = True)
tempo_dia['time'] = pd.to_datetime(tempo_dia['time'], utc = True)

In [2]:
tempo_minuto

       id_time                      time
0            0 2023-10-09 00:03:49+00:00
1            1 2023-10-09 00:13:49+00:00
2            2 2023-10-09 00:23:49+00:00
3            3 2023-10-09 00:33:49+00:00
4            4 2023-10-09 00:43:49+00:00
...        ...                       ...
40293    40293 2024-07-14 21:10:52+00:00
40294    40294 2024-07-14 21:20:52+00:00
40295    40295 2024-07-14 21:30:52+00:00
40296    40296 2024-07-14 21:40:52+00:00
40297    40297 2024-07-14 21:50:52+00:00

[40298 rows x 2 columns]

In [44]:
tempo_minuto[tempo_minuto['id_time'] > 14610]

       id_time                      time
14611    14611 2024-01-18 12:14:56+00:00
14612    14612 2024-01-18 12:24:56+00:00
14613    14613 2024-01-18 12:34:56+00:00
14614    14614 2024-01-18 12:50:52+00:00
14615    14615 2024-01-18 13:00:52+00:00
...        ...                       ...
40293    40293 2024-07-14 21:10:52+00:00
40294    40294 2024-07-14 21:20:52+00:00
40295    40295 2024-07-14 21:30:52+00:00
40296    40296 2024-07-14 21:40:52+00:00
40297    40297 2024-07-14 21:50:52+00:00

[25687 rows x 2 columns]

In [9]:
lista_minutos = list(tempo_minuto['time'].dt.minute)
lista_IDS_minutos = list(tempo_minuto['id_time'])
lista_horas = list(tempo_hora['time'].dt.hour)
lista_IDS_horas = list(tempo_hora['id_time'])

lista_dias = list(tempo_dia['time'].dt.day)
lista_IDS_dias = list(tempo_dia['id_time'])

diff_d = {}
for i in range( len(lista_dias) -1):
    diff_d[lista_IDS_dias[i+1]] = lista_dias[i+1] - lista_dias[i]

diff_m = {}
for i in range( len(lista_minutos) -1):
    diff_m[lista_IDS_minutos[i+1]] = lista_minutos[i+1] - lista_minutos[i]

diff_h = {}
for i in range( len(lista_horas) -1):
    diff_h[lista_IDS_horas[i+1]] = lista_horas[i+1] - lista_horas[i]

print("minutos")
for m in list(diff_m.keys()):
    if not((int(m)%6 == 0 and int(diff_m[m]) == -50) or int(diff_m[m]) == 10):
        print(f"{m}  :  {diff_m[m]}")

print("hora")
for h in list(diff_h.keys()):
    if not((int(h)%24 == 0 and int(diff_h[h]) == -23) or int(diff_h[h]) == 1):
        print(f"{h}  :  {diff_h[h]}")

print("dia")
for d in list(diff_d.keys()):
    if not((int(d)%31 == 0 and int(diff_d[d]) == -30 ) or int(diff_d[d]) == 1):
        print(f"{d}  :  {diff_d[d]}")

minutos
3647  :  11
14614  :  16
14615  :  -50
14621  :  -50
14627  :  -50
14633  :  -50
14639  :  -50
14645  :  -50
14651  :  -50
14657  :  -50
14663  :  -50
14669  :  -50
14675  :  -50
14681  :  -50
14687  :  -50
14693  :  -50
14699  :  -50
14705  :  -50
14711  :  -50
14717  :  -50
14723  :  -50
14729  :  -50
14735  :  -50
14741  :  -50
14747  :  -50
14753  :  -50
14759  :  -50
14765  :  -50
14771  :  -50
14777  :  -50
14783  :  -50
14789  :  -50
14795  :  -50
14801  :  -50
14807  :  -50
14813  :  -50
14819  :  -50
14825  :  -50
14831  :  -50
14837  :  -50
14843  :  -50
14849  :  -50
14855  :  -50
14861  :  -50
14867  :  -50
14873  :  -50
14879  :  -50
14885  :  -50
14891  :  -50
14897  :  -50
14903  :  -50
14909  :  -50
14915  :  -50
14921  :  -50
14927  :  -50
14933  :  -50
14939  :  -50
14945  :  -50
14951  :  -50
14957  :  -50
14963  :  -50
14969  :  -50
14975  :  -50
14981  :  -50
14987  :  -50
14993  :  -50
14999  :  -50
15005  :  -50
15011  :  -50
15017  :  -50
15023  :  -50
15029  :  -50
15035  :  -50
15041  :  -50
15047  :  -50
15053  :  -50
15059  :  -50
15065  :  -50
15071  :  -50
15077  :  -50
15083  :  -50
15089  :  -50
15095  :  -50
15101  :  -50
15107  :  -50
15113  :  -50
15119  :  -50
15125  :  -50
15131  :  -50
15137  :  -50
15143  :  -50
15149  :  -50
15155  :  -50
15161  :  -50
15167  :  -50
15173  :  -50
15179  :  -50
15185  :  -50
15191  :  -50
15197  :  -50
15203  :  -50
15209  :  -50
15215  :  -50
15221  :  -50
15227  :  -50
15233  :  -50
15239  :  -50
15245  :  -50
15251  :  -50
15257  :  -50
15263  :  -50
15269  :  -50
15275  :  -50
15281  :  -50
15287  :  -50
15293  :  -50
15299  :  -50
15305  :  -50
15311  :  -50
15317  :  -50
15323  :  -50
15329  :  -50
15335  :  -50
15341  :  -50
15347  :  -50
15353  :  -50
15359  :  -50
15365  :  -50
15371  :  -50
15377  :  -50
15383  :  -50
15389  :  -50
15395  :  -50
15401  :  -50
15407  :  -50
15413  :  -50
15419  :  -50
15425  :  -50
15431  :  -50
15437  :  -50
15443  :  -50
15449  :  -50
15455  :  -50
15461  :  -50
15467  :  -50
15473  :  -50
15479  :  -50
15485  :  -50
15491  :  -50
15497  :  -50
15503  :  -50
15509  :  -50
15515  :  -50
15521  :  -50
15527  :  -50
15533  :  -50
15539  :  -50
15545  :  -50
15551  :  -50
15557  :  -50
15563  :  -50
15569  :  -50
15575  :  -50
15581  :  -50
15587  :  -50
15593  :  -50
15599  :  -50
15605  :  -50
15611  :  -50
15617  :  -50
15623  :  -50
15629  :  -50
15635  :  -50
15641  :  -50
15647  :  -50
15653  :  -50
15659  :  -50
15665  :  -50
15671  :  -50
15677  :  -50
15683  :  -50
15689  :  -50
15695  :  -50
15701  :  -50
15707  :  -50
15713  :  -50
15719  :  -50
15725  :  -50
15731  :  -50
15737  :  -50
15743  :  -50
15749  :  -50
15755  :  -50
15761  :  -50
15767  :  -50
15773  :  -50
15779  :  -50
15785  :  -50
15791  :  -50
15797  :  -50
15803  :  -50
15809  :  -50
15815  :  -50
15821  :  -50
15827  :  -50
15833  :  -50
15839  :  -50
15845  :  -50
15851  :  -50
15857  :  -50
15863  :  -50
15869  :  -50
15875  :  -50
15881  :  -50
15887  :  -50
15893  :  -50
15899  :  -50
15905  :  -50
15911  :  -50
15917  :  -50
15923  :  -50
15929  :  -50
15935  :  -50
15941  :  -50
15947  :  -50
15953  :  -50
15959  :  -50
15965  :  -50
15971  :  -50
15977  :  -50
15983  :  -50
15989  :  -50
15995  :  -50
16001  :  -50
16007  :  -50
16013  :  -50
16019  :  -50
16025  :  -50
16031  :  -50
16037  :  -50
16043  :  -50
16049  :  -50
16055  :  -50
16061  :  -50
16067  :  -50
16073  :  -50
16079  :  -50
16085  :  -50
16091  :  -50
16097  :  -50
16103  :  -50
16109  :  -50
16115  :  -50
16121  :  -50
16127  :  -50
16133  :  -50
16139  :  -50
16145  :  -50
16151  :  -50
16157  :  -50
16163  :  -50
16169  :  -50
16175  :  -50
16181  :  -50
16187  :  -50
16193  :  -50
16199  :  -50
16205  :  -50
16211  :  -50
16217  :  -50
16223  :  -50
16229  :  -50
16235  :  -50
16241  :  -50
16247  :  -50
16253  :  -50
16259  :  -50
16265  :  -50
16271  :  -50
16277  :  -50
16283  :  -50
16289  :  -50
16295  :  -50
16301  :  -50
16307  :  -50
16313  :  -50
16319  :  -50
16325  :  -50
16331  :  -50
16337  :  -50
16343  :  -50
16349  :  -50
16355  :  -50
16361  :  -50
16367  :  -50
16373  :  -50
16379  :  -50
16385  :  -50
16391  :  -50
16397  :  -50
16403  :  -50
16409  :  -50
16415  :  -50
16421  :  -50
16427  :  -50
16433  :  -50
16439  :  -50
16445  :  -50
16451  :  -50
16457  :  -50
16463  :  -50
16469  :  -50
16475  :  -50
16481  :  -50
16487  :  -50
16493  :  -50
16499  :  -50
16505  :  -50
16511  :  -50
16517  :  -50
16523  :  -50
16529  :  -50
16535  :  -50
16541  :  -50
16547  :  -50
16553  :  -50
16559  :  -50
16565  :  -50
16571  :  -50
16577  :  -50
16583  :  -50
16589  :  -50
16595  :  -50
16601  :  -50
16607  :  -50
16613  :  -50
16619  :  -50
16625  :  -50
16631  :  -50
16637  :  -50
16643  :  -50
16649  :  -50
16655  :  -50
16661  :  -50
16667  :  -50
16673  :  -50
16679  :  -50
16685  :  -50
16691  :  -50
16697  :  -50
16703  :  -50
16709  :  -50
16715  :  -50
16721  :  -50
16727  :  -50
16733  :  -50
16739  :  -50
16745  :  -50
16751  :  -50
16757  :  -50
16763  :  -50
16769  :  -50
16775  :  -50
16781  :  -50
16787  :  -50
16793  :  -50
16799  :  -50
16805  :  -50
16811  :  -50
16817  :  -50
16823  :  -50
16829  :  -50
16835  :  -50
16841  :  -50
16847  :  -50
16853  :  -50
16859  :  -50
16865  :  -50
16871  :  -50
16877  :  -50
16883  :  -50
16889  :  -50
16895  :  -50
16901  :  -50
16907  :  -50
16913  :  -50
16919  :  -50
16925  :  -50
16931  :  -50
16937  :  -50
16943  :  -50
16949  :  -50
16955  :  -50
16961  :  -50
16967  :  -50
16973  :  -50
16979  :  -50
16985  :  -50
16991  :  -50
16997  :  -50
17003  :  -50
17009  :  -50
17015  :  -50
17021  :  -50
17027  :  -50
17033  :  -50
17039  :  -50
17045  :  -50
17051  :  -50
17057  :  -50
17063  :  -50
17069  :  -50
17075  :  -50
17081  :  -50
17087  :  -50
17093  :  -50
17099  :  -50
17105  :  -50
17111  :  -50
17117  :  -50
17123  :  -50
17129  :  -50
17135  :  -50
17141  :  -50
17147  :  -50
17153  :  -50
17159  :  -50
17165  :  -50
17171  :  -50
17177  :  -50
17183  :  -50
17189  :  -50
17195  :  -50
17201  :  -50
17207  :  -50
17213  :  -50
17219  :  -50
17225  :  -50
17231  :  -50
17237  :  -50
17243  :  -50
17249  :  -50
17255  :  -50
17261  :  -50
17267  :  -50
17273  :  -50
17279  :  -50
17285  :  -50
17291  :  -50
17297  :  -50
17303  :  -50
17309  :  -50
17315  :  -50
17321  :  -50
17327  :  -50
17333  :  -50
17339  :  -50
17345  :  -50
17351  :  -50
17357  :  -50
17363  :  -50
17369  :  -50
17375  :  -50
17381  :  -50
17387  :  -50
17393  :  -50
17399  :  -50
17405  :  -50
17411  :  -50
17417  :  -50
17423  :  -50
17429  :  -50
17435  :  -50
17441  :  -50
17447  :  -50
17453  :  -50
17459  :  -50
17465  :  -50
17471  :  -50
17477  :  -50
17483  :  -50
17489  :  -50
17495  :  -50
17501  :  -50
17507  :  -50
17513  :  -50
17519  :  -50
17525  :  -50
17531  :  -50
17537  :  -50
17543  :  -50
17549  :  -50
17555  :  -50
17561  :  -50
17567  :  -50
17573  :  -50
17579  :  -50
17585  :  -50
17591  :  -50
17597  :  -50
17603  :  -50
17609  :  -50
17615  :  -50
17621  :  -50
17627  :  -50
17633  :  -50
17639  :  -50
17645  :  -50
17651  :  -50
17657  :  -50
17663  :  -50
17669  :  -50
17675  :  -50
17681  :  -50
17687  :  -50
17693  :  -50
17699  :  -50
17705  :  -50
17711  :  -50
17717  :  -50
17723  :  -50
17729  :  -50
17735  :  -50
17741  :  -50
17747  :  -50
17753  :  -50
17759  :  -50
17765  :  -50
17771  :  -50
17777  :  -50
17783  :  -50
17789  :  -50
17795  :  -50
17801  :  -50
17807  :  -50
17813  :  -50
17819  :  -50
17825  :  -50
17831  :  -50
17837  :  -50
17843  :  -50
17849  :  -50
17855  :  -50
17861  :  -50
17867  :  -50
17873  :  -50
17879  :  -50
17885  :  -50
17891  :  -50
17897  :  -50
17903  :  -50
17909  :  -50
17915  :  -50
17921  :  -50
17927  :  -50
17933  :  -50
17939  :  -50
17945  :  -50
17951  :  -50
17957  :  -50
17963  :  -50
17969  :  -50
17975  :  -50
17981  :  -50
17987  :  -50
17993  :  -50
17999  :  -50
18005  :  -50
18011  :  -50
18017  :  -50
18023  :  -50
18029  :  -50
18035  :  -50
18041  :  -50
18047  :  -50
18053  :  -50
18059  :  -50
18065  :  -50
18071  :  -50
18077  :  -50
18083  :  -50
18089  :  -50
18095  :  -50
18101  :  -50
18107  :  -50
18113  :  -50
18119  :  -50
18125  :  -50
18131  :  -50
18137  :  -50
18143  :  -50
18149  :  -50
18155  :  -50
18161  :  -50
18167  :  -50
18173  :  -50
18179  :  -50
18185  :  -50
18191  :  -50
18197  :  -50
18203  :  -50
18209  :  -50
18215  :  -50
18221  :  -50
18227  :  -50
18233  :  -50
18239  :  -50
18245  :  -50
18251  :  -50
18257  :  -50
18263  :  -50
18269  :  -50
18275  :  -50
18281  :  -50
18287  :  -50
18293  :  -50
18299  :  -50
18305  :  -50
18311  :  -50
18317  :  -50
18323  :  -50
18329  :  -50
18335  :  -50
18341  :  -50
18347  :  -50
18353  :  -50
18359  :  -50
18365  :  -50
18371  :  -50
18377  :  -50
18383  :  -50
18389  :  -50
18395  :  -50
18401  :  -50
18407  :  -50
18413  :  -50
18419  :  -50
18425  :  -50
18431  :  -50
18437  :  -50
18443  :  -50
18449  :  -50
18455  :  -50
18461  :  -50
18467  :  -50
18473  :  -50
18479  :  -50
18485  :  -50
18491  :  -50
18497  :  -50
18503  :  -50
18509  :  -50
18515  :  -50
18521  :  -50
18527  :  -50
18533  :  -50
18539  :  -50
18545  :  -50
18551  :  -50
18557  :  -50
18563  :  -50
18569  :  -50
18575  :  -50
18581  :  -50
18587  :  -50
18593  :  -50
18599  :  -50
18605  :  -50
18611  :  -50
18617  :  -50
18623  :  -50
18629  :  -50
18635  :  -50
18641  :  -50
18647  :  -50
18653  :  -50
18659  :  -50
18665  :  -50
18671  :  -50
18677  :  -50
18683  :  -50
18689  :  -50
18695  :  -50
18701  :  -50
18707  :  -50
18713  :  -50
18719  :  -50
18725  :  -50
18731  :  -50
18737  :  -50
18743  :  -50
18749  :  -50
18755  :  -50
18761  :  -50
18767  :  -50
18773  :  -50
18779  :  -50
18785  :  -50
18791  :  -50
18797  :  -50
18803  :  -50
18809  :  -50
18815  :  -50
18821  :  -50
18827  :  -50
18833  :  -50
18839  :  -50
18845  :  -50
18851  :  -50
18857  :  -50
18863  :  -50
18869  :  -50
18875  :  -50
18881  :  -50
18887  :  -50
18893  :  -50
18899  :  -50
18905  :  -50
18911  :  -50
18917  :  -50
18923  :  -50
18929  :  -50
18935  :  -50
18941  :  -50
18947  :  -50
18953  :  -50
18959  :  -50
18965  :  -50
18971  :  -50
18977  :  -50
18983  :  -50
18989  :  -50
18995  :  -50
19001  :  -50
19007  :  -50
19013  :  -50
19019  :  -50
19025  :  -50
19031  :  -50
19037  :  -50
19043  :  -50
19049  :  -50
19055  :  -50
19061  :  -50
19067  :  -50
19073  :  -50
19079  :  -50
19085  :  -50
19091  :  -50
19097  :  -50
19103  :  -50
19109  :  -50
19115  :  -50
19121  :  -50
19127  :  -50
19133  :  -50
19139  :  -50
19145  :  -50
19151  :  -50
19157  :  -50
19163  :  -50
19169  :  -50
19175  :  -50
19181  :  -50
19187  :  -50
19193  :  -50
19199  :  -50
19205  :  -50
19211  :  -50
19217  :  -50
19223  :  -50
19229  :  -50
19235  :  -50
19241  :  -50
19247  :  -50
19253  :  -50
19259  :  -50
19265  :  -50
19271  :  -50
19277  :  -50
19283  :  -50
19289  :  -50
19295  :  -50
19301  :  -50
19307  :  -50
19313  :  -50
19319  :  -50
19325  :  -50
19331  :  -50
19337  :  -50
19343  :  -50
19349  :  -50
19355  :  -50
19361  :  -50
19367  :  -50
19373  :  -50
19379  :  -50
19385  :  -50
19391  :  -50
19397  :  -50
19403  :  -50
19409  :  -50
19415  :  -50
19421  :  -50
19427  :  -50
19433  :  -50
19439  :  -50
19445  :  -50
19451  :  -50
19457  :  -50
19463  :  -50
19469  :  -50
19475  :  -50
19481  :  -50
19487  :  -50
19493  :  -50
19499  :  -50
19505  :  -50
19511  :  -50
19517  :  -50
19523  :  -50
19529  :  -50
19535  :  -50
19541  :  -50
19547  :  -50
19553  :  -50
19559  :  -50
19565  :  -50
19571  :  -50
19577  :  -50
19583  :  -50
19589  :  -50
19595  :  -50
19601  :  -50
19607  :  -50
19613  :  -50
19619  :  -50
19625  :  -50
19631  :  -50
19637  :  -50
19643  :  -50
19649  :  -50
19655  :  -50
19661  :  -50
19667  :  -50
19673  :  -50
19679  :  -50
19685  :  -50
19691  :  -50
19697  :  -50
19703  :  -50
19709  :  -50
19715  :  -50
19721  :  -50
19727  :  -50
19733  :  -50
19739  :  -50
19745  :  -50
19751  :  -50
19757  :  -50
19763  :  -50
19769  :  -50
19775  :  -50
19781  :  -50
19787  :  -50
19793  :  -50
19799  :  -50
19805  :  -50
19811  :  -50
19817  :  -50
19823  :  -50
19829  :  -50
19835  :  -50
19841  :  -50
19847  :  -50
19853  :  -50
19859  :  -50
19865  :  -50
19871  :  -50
19877  :  -50
19883  :  -50
19889  :  -50
19895  :  -50
19901  :  -50
19907  :  -50
19913  :  -50
19919  :  -50
19925  :  -50
19931  :  -50
19937  :  -50
19943  :  -50
19949  :  -50
19955  :  -50
19961  :  -50
19967  :  -50
19973  :  -50
19979  :  -50
19985  :  -50
19991  :  -50
19997  :  -50
20003  :  -50
20009  :  -50
20015  :  -50
20021  :  -50
20027  :  -50
20033  :  -50
20039  :  -50
20045  :  -50
20051  :  -50
20057  :  -50
20063  :  -50
20069  :  -50
20075  :  -50
20081  :  -50
20087  :  -50
20093  :  -50
20099  :  -50
20105  :  -50
20111  :  -50
20117  :  -50
20123  :  -50
20129  :  -50
20135  :  -50
20141  :  -50
20147  :  -50
20153  :  -50
20159  :  -50
20165  :  -50
20171  :  -50
20177  :  -50
20183  :  -50
20189  :  -50
20195  :  -50
20201  :  -50
20207  :  -50
20213  :  -50
20219  :  -50
20225  :  -50
20231  :  -50
20237  :  -50
20243  :  -50
20249  :  -50
20255  :  -50
20261  :  -50
20267  :  -50
20273  :  -50
20279  :  -50
20285  :  -50
20291  :  -50
20297  :  -50
20303  :  -50
20309  :  -50
20315  :  -50
20321  :  -50
20327  :  -50
20333  :  -50
20339  :  -50
20345  :  -50
20351  :  -50
20357  :  -50
20363  :  -50
20369  :  -50
20375  :  -50
20381  :  -50
20387  :  -50
20393  :  -50
20399  :  -50
20405  :  -50
20411  :  -50
20417  :  -50
20423  :  -50
20429  :  -50
20435  :  -50
20441  :  -50
20447  :  -50
20453  :  -50
20459  :  -50
20465  :  -50
20471  :  -50
20477  :  -50
20483  :  -50
20489  :  -50
20495  :  -50
20501  :  -50
20507  :  -50
20513  :  -50
20519  :  -50
20525  :  -50
20531  :  -50
20537  :  -50
20543  :  -50
20549  :  -50
20555  :  -50
20561  :  -50
20567  :  -50
20573  :  -50
20579  :  -50
20585  :  -50
20591  :  -50
20597  :  -50
20603  :  -50
20609  :  -50
20615  :  -50
20621  :  -50
20627  :  -50
20633  :  -50
20639  :  -50
20645  :  -50
20651  :  -50
20657  :  -50
20663  :  -50
20669  :  -50
20675  :  -50
20681  :  -50
20687  :  -50
20693  :  -50
20699  :  -50
20705  :  -50
20711  :  -50
20717  :  -50
20723  :  -50
20729  :  -50
20735  :  -50
20741  :  -50
20747  :  -50
20753  :  -50
20759  :  -50
20765  :  -50
20771  :  -50
20777  :  -50
20783  :  -50
20789  :  -50
20795  :  -50
20801  :  -50
20807  :  -50
20813  :  -50
20819  :  -50
20825  :  -50
20831  :  -50
20837  :  -50
20843  :  -50
20849  :  -50
20855  :  -50
20861  :  -50
20867  :  -50
20873  :  -50
20879  :  -50
20885  :  -50
20891  :  -50
20897  :  -50
20903  :  -50
20909  :  -50
20915  :  -50
20921  :  -50
20927  :  -50
20933  :  -50
20939  :  -50
20945  :  -50
20951  :  -50
20957  :  -50
20963  :  -50
20969  :  -50
20975  :  -50
20981  :  -50
20987  :  -50
20993  :  -50
20999  :  -50
21005  :  -50
21011  :  -50
21017  :  -50
21023  :  -50
21029  :  -50
21035  :  -50
21041  :  -50
21047  :  -50
21053  :  -50
21059  :  -50
21065  :  -50
21071  :  -50
21077  :  -50
21083  :  -50
21089  :  -50
21095  :  -50
21101  :  -50
21107  :  -50
21113  :  -50
21119  :  -50
21125  :  -50
21131  :  -50
21137  :  -50
21143  :  -50
21149  :  -50
21155  :  -50
21161  :  -50
21167  :  -50
21173  :  -50
21179  :  -50
21185  :  -50
21191  :  -50
21197  :  -50
21203  :  -50
21209  :  -50
21215  :  -50
21221  :  -50
21227  :  -50
21233  :  -50
21239  :  -50
21245  :  -50
21251  :  -50
21257  :  -50
21263  :  -50
21269  :  -50
21275  :  -50
21281  :  -50
21287  :  -50
21293  :  -50
21299  :  -50
21305  :  -50
21311  :  -50
21317  :  -50
21323  :  -50
21329  :  -50
21335  :  -50
21341  :  -50
21347  :  -50
21353  :  -50
21359  :  -50
21365  :  -50
21371  :  -50
21377  :  -50
21383  :  -50
21389  :  -50
21395  :  -50
21401  :  -50
21407  :  -50
21413  :  -50
21419  :  -50
21425  :  -50
21431  :  -50
21437  :  -50
21443  :  -50
21449  :  -50
21455  :  -50
21461  :  -50
21467  :  -50
21473  :  -50
21479  :  -50
21485  :  -50
21491  :  -50
21497  :  -50
21503  :  -50
21509  :  -50
21515  :  -50
21521  :  -50
21527  :  -50
21533  :  -50
21539  :  -50
21545  :  -50
21551  :  -50
21557  :  -50
21563  :  -50
21569  :  -50
21575  :  -50
21581  :  -50
21587  :  -50
21593  :  -50
21599  :  -50
21605  :  -50
21611  :  -50
21617  :  -50
21623  :  -50
21629  :  -50
21635  :  -50
21641  :  -50
21647  :  -50
21653  :  -50
21659  :  -50
21665  :  -50
21671  :  -50
21677  :  -50
21683  :  -50
21689  :  -50
21695  :  -50
21701  :  -50
21707  :  -50
21713  :  -50
21719  :  -50
21725  :  -50
21731  :  -50
21737  :  -50
21743  :  -50
21749  :  -50
21755  :  -50
21761  :  -50
21767  :  -50
21773  :  -50
21779  :  -50
21785  :  -50
21791  :  -50
21797  :  -50
21803  :  -50
21809  :  -50
21815  :  -50
21821  :  -50
21827  :  -50
21833  :  -50
21839  :  -50
21845  :  -50
21851  :  -50
21857  :  -50
21863  :  -50
21869  :  -50
21875  :  -50
21881  :  -50
21887  :  -50
21893  :  -50
21899  :  -50
21905  :  -50
21911  :  -50
21917  :  -50
21923  :  -50
21929  :  -50
21935  :  -50
21941  :  -50
21947  :  -50
21953  :  -50
21959  :  -50
21965  :  -50
21971  :  -50
21977  :  -50
21983  :  -50
21989  :  -50
21995  :  -50
22001  :  -50
22007  :  -50
22013  :  -50
22019  :  -50
22025  :  -50
22031  :  -50
22037  :  -50
22043  :  -50
22049  :  -50
22055  :  -50
22061  :  -50
22067  :  -50
22073  :  -50
22079  :  -50
22085  :  -50
22091  :  -50
22097  :  -50
22103  :  -50
22109  :  -50
22115  :  -50
22121  :  -50
22127  :  -50
22133  :  -50
22139  :  -50
22145  :  -50
22151  :  -50
22157  :  -50
22163  :  -50
22169  :  -50
22175  :  -50
22181  :  -50
22187  :  -50
22193  :  -50
22199  :  -50
22205  :  -50
22211  :  -50
22217  :  -50
22223  :  -50
22229  :  -50
22235  :  -50
22241  :  -50
22247  :  -50
22253  :  -50
22259  :  -50
22265  :  -50
22271  :  -50
22277  :  -50
22283  :  -50
22289  :  -50
22295  :  -50
22301  :  -50
22307  :  -50
22313  :  -50
22319  :  -50
22325  :  -50
22331  :  -50
22337  :  -50
22343  :  -50
22349  :  -50
22355  :  -50
22361  :  -50
22367  :  -50
22373  :  -50
22379  :  -50
22385  :  -50
22391  :  -50
22397  :  -50
22403  :  -50
22409  :  -50
22415  :  -50
22421  :  -50
22427  :  -50
22433  :  -50
22439  :  -50
22445  :  -50
22451  :  -50
22457  :  -50
22463  :  -50
22469  :  -50
22475  :  -50
22481  :  -50
22487  :  -50
22493  :  -50
22499  :  -50
22505  :  -50
22511  :  -50
22517  :  -50
22523  :  -50
22529  :  -50
22535  :  -50
22541  :  -50
22547  :  -50
22553  :  -50
22559  :  -50
22565  :  -50
22571  :  -50
22577  :  -50
22583  :  -50
22589  :  -50
22595  :  -50
22601  :  -50
22607  :  -50
22613  :  -50
22619  :  -50
22625  :  -50
22631  :  -50
22637  :  -50
22643  :  -50
22649  :  -50
22655  :  -50
22661  :  -50
22667  :  -50
22673  :  -50
22679  :  -50
22685  :  -50
22691  :  -50
22697  :  -50
22703  :  -50
22709  :  -50
22715  :  -50
22721  :  -50
22727  :  -50
22733  :  -50
22739  :  -50
22745  :  -50
22751  :  -50
22757  :  -50
22763  :  -50
22769  :  -50
22775  :  -50
22781  :  -50
22787  :  -50
22793  :  -50
22799  :  -50
22805  :  -50
22811  :  -50
22817  :  -50
22823  :  -50
22829  :  -50
22835  :  -50
22841  :  -50
22847  :  -50
22853  :  -50
22859  :  -50
22865  :  -50
22871  :  -50
22877  :  -50
22883  :  -50
22889  :  -50
22895  :  -50
22901  :  -50
22907  :  -50
22913  :  -50
22919  :  -50
22925  :  -50
22931  :  -50
22937  :  -50
22943  :  -50
22949  :  -50
22955  :  -50
22961  :  -50
22967  :  -50
22973  :  -50
22979  :  -50
22985  :  -50
22991  :  -50
22997  :  -50
23003  :  -50
23009  :  -50
23015  :  -50
23021  :  -50
23027  :  -50
23033  :  -50
23039  :  -50
23045  :  -50
23051  :  -50
23057  :  -50
23063  :  -50
23069  :  -50
23075  :  -50
23081  :  -50
23087  :  -50
23093  :  -50
23099  :  -50
23105  :  -50
23111  :  -50
23117  :  -50
23123  :  -50
23129  :  -50
23135  :  -50
23141  :  -50
23147  :  -50
23153  :  -50
23159  :  -50
23165  :  -50

In [10]:
print(len(lista_IDS_minutos))
print(len(lista_IDS_horas))
print(len(lista_IDS_dias))

40298
6718
280

In [11]:
lista_minutos = list(tempo_minuto[tempo_minuto['id_time'] > 14614 ]['time'].dt.minute)
lista_IDS_minutos = list(tempo_minuto['id_time'])


diff_m = {}
for i in range( len(lista_minutos) -1):
    diff_m[lista_IDS_minutos[i+1]] = lista_minutos[i+1] - lista_minutos[i]


for m in list(diff_m.keys()):
    if not((int(m+)%6 == 0 and int(diff_m[m]) == -50) or int(diff_m[m]) == 10):
        print(f"{m}  :  {diff_m[m]}")

25448  :  20
25451  :  -50
25457  :  -50
25463  :  -50
25469  :  -50
25475  :  -50
25481  :  -50
25486  :  -30
25491  :  -50
25497  :  -50
25503  :  -50
25509  :  -50
25515  :  -50
25521  :  -50
25527  :  -50
25533  :  -50
25539  :  -50
25545  :  -50
25551  :  -50
25557  :  -50
25563  :  -50
25569  :  -50
25575  :  -50
25581  :  -50
25587  :  -50
25593  :  -50
25599  :  -50
25605  :  -50
25611  :  -50
25617  :  -50
25623  :  -50
25629  :  -50
25635  :  -50
25641  :  -50
25647  :  -50
25653  :  -50
25659  :  -50
25665  :  -50
25671  :  -50
25677  :  -50

In [13]:
tempo_minuto[tempo_minuto['id_time'] > 25446]

       id_time                      time
25447    25447 2024-04-02 18:20:52+00:00
25448    25448 2024-04-02 18:30:52+00:00
25449    25449 2024-04-02 18:40:52+00:00
25450    25450 2024-04-02 18:50:52+00:00
25451    25451 2024-04-02 19:00:52+00:00
...        ...                       ...
40293    40293 2024-07-14 21:10:52+00:00
40294    40294 2024-07-14 21:20:52+00:00
40295    40295 2024-07-14 21:30:52+00:00
40296    40296 2024-07-14 21:40:52+00:00
40297    40297 2024-07-14 21:50:52+00:00

[14851 rows x 2 columns]